### PR TITLE
Update cloudrail 1.3

### PR DESCRIPTION
**Pull request by yi2020**

### CODE REVIEW

**Comment by yi2020** [comment]
@owenrumney can you review to keep me honest?

**Comment by yi2020** [comment]
Apologies for the weird git history, I accidentally pushed this to main initially instead of its own branch.

**Review by owenrumney — APPROVED** [review]
looks okay to me. I guess we need to pull out finger out again for tfsec

**Comment by yi2020** [comment]
@owenrumney guess so! :) Nothing to energize things like a healthy competition.

**Pull request merged**
